# Generated by Django 6.0.2 on 2026-02-18 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ECGUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="ecg_uploads/")),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "patient_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("patient_age", models.PositiveIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="UPLOADED",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ECGResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnosis", models.CharField(max_length=150)),
                ("confidence", models.FloatField()),
                ("severity", models.CharField(max_length=20)),
                ("heart_attack_risk", models.CharField(max_length=20)),
                ("heart_attack_probability", models.FloatField(default=0.0)),
                ("heart_rate", models.IntegerField(blank=True, null=True)),
                ("pr_interval", models.FloatField(blank=True, null=True)),
                ("qrs_duration", models.FloatField(blank=True, null=True)),
                ("qt_interval", models.FloatField(blank=True, null=True)),
                ("predictions_json", models.JSONField(default=dict)),
                ("findings", models.TextField(blank=True, default="")),
                ("recommendations", models.TextField(blank=True, default="")),
                ("emergency_alert", models.BooleanField(default=False)),
                ("processing_time", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "upload",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="heartguard.ecgupload",
                    ),
                ),
            ],
        ),
    ]
