# Generated by Django 4.2.29 on 2026-03-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heartguard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ecgresult",
            name="recommendation_steps",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
