# Generated by Django 4.2.29 on 2026-03-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heartguard", "0002_ecgresult_recommendation_steps"),
    ]

    operations = [
        migrations.AddField(
            model_name="ecgresult",
            name="tabular_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ecgupload",
            name="chest_pain_type",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Typical Angina"),
                    (2, "Atypical Angina"),
                    (3, "Non-Anginal Pain"),
                    (4, "Asymptomatic"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ecgupload",
            name="cholesterol",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ecgupload",
            name="exercise_angina",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ecgupload",
            name="fasting_bs",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ecgupload",
            name="max_heart_rate",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ecgupload",
            name="oldpeak",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ecgupload",
            name="patient_sex",
            field=models.IntegerField(
                blank=True, choices=[(1, "Male"), (0, "Female")], null=True
            ),
        ),
        migrations.AddField(
            model_name="ecgupload",
            name="resting_bp",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ecgupload",
            name="resting_ecg",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Normal"),
                    (1, "ST-T Wave Abnormality"),
                    (2, "Left Ventricular Hypertrophy"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ecgupload",
            name="st_slope",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Upsloping"), (2, "Flat"), (3, "Downsloping")],
                null=True,
            ),
        ),
    ]
